// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeloTime.Module.Timing.Storage;

#nullable disable

namespace VeloTime.Module.Timing.Migrations
{
    [DbContext(typeof(TimingDbContext))]
    partial class TimingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("timing")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeloTime.Module.Timing.Model.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Facility")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimingSystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimingSystemId");

                    b.ToTable("Installation", "timing");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.Passing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("LowBattery")
                        .HasColumnType("boolean");

                    b.Property<bool>("LowHits")
                        .HasColumnType("boolean");

                    b.Property<bool>("LowStrength")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TimingPointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransponderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimingPointId");

                    b.HasIndex("TransponderId");

                    b.ToTable("Passing", "timing");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.TimingPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("TimingPoint", "timing");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.TimingSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TimingSystem", "timing");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.Transponder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Transponder", "timing");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.TransponderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransponderType", "timing");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.Installation", b =>
                {
                    b.HasOne("VeloTime.Module.Timing.Model.TimingSystem", "TimingSystem")
                        .WithMany("Installations")
                        .HasForeignKey("TimingSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimingSystem");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.Passing", b =>
                {
                    b.HasOne("VeloTime.Module.Timing.Model.TimingPoint", "TimingPoint")
                        .WithMany()
                        .HasForeignKey("TimingPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeloTime.Module.Timing.Model.Transponder", "Transponder")
                        .WithMany()
                        .HasForeignKey("TransponderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimingPoint");

                    b.Navigation("Transponder");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.TimingPoint", b =>
                {
                    b.HasOne("VeloTime.Module.Timing.Model.Installation", "Installation")
                        .WithMany("TimingPoints")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.Transponder", b =>
                {
                    b.HasOne("VeloTime.Module.Timing.Model.TransponderType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.Installation", b =>
                {
                    b.Navigation("TimingPoints");
                });

            modelBuilder.Entity("VeloTime.Module.Timing.Model.TimingSystem", b =>
                {
                    b.Navigation("Installations");
                });
#pragma warning restore 612, 618
        }
    }
}
