// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeloTime.Module.Statistics.Storage;

#nullable disable

namespace VeloTime.Module.Statistics.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    [Migration("20260203191604_statistics_multi")]
    partial class statistics_multi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("statistics")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.MultiStatisticsItemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ParentConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_config_id");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.Property<Guid>("StatisticsItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("statistics_item_id");

                    b.HasKey("Id")
                        .HasName("pk_multi_statistics_item_config");

                    b.HasIndex("ParentConfigId")
                        .HasDatabaseName("ix_multi_statistics_item_config_parent_config_id");

                    b.HasIndex("StatisticsItemId", "ParentConfigId")
                        .HasDatabaseName("ix_multi_statistics_item_config_statistics_item_id_parent_conf");

                    b.ToTable("multi_statistics_item_config", "statistics");
                });

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoursePointEndId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_point_end_id");

                    b.Property<Guid>("CoursePointStartId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_point_start_id");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_end");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_start");

                    b.Property<Guid>("TransponderId")
                        .HasColumnType("uuid")
                        .HasColumnName("transponder_id");

                    b.HasKey("Id")
                        .HasName("pk_sample");

                    b.ToTable("sample", "statistics");
                });

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.SimpleStatisticsItemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoursePointEnd")
                        .HasColumnType("uuid")
                        .HasColumnName("course_point_end");

                    b.Property<Guid>("CoursePointStart")
                        .HasColumnType("uuid")
                        .HasColumnName("course_point_start");

                    b.Property<Guid>("StatisticsItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("statistics_item_id");

                    b.HasKey("Id")
                        .HasName("pk_simple_statistics_item_config");

                    b.HasIndex("StatisticsItemId", "CoursePointStart", "CoursePointEnd")
                        .HasDatabaseName("ix_simple_statistics_item_config_statistics_item_id_course_poi");

                    b.ToTable("simple_statistics_item_config", "statistics");
                });

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.StatisticsEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<Guid>("StatisticsItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("statistics_item_id");

                    b.Property<Guid?>("StatsProfileUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("stats_profile_user_id");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_end");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_start");

                    b.Property<Guid>("TransponderId")
                        .HasColumnType("uuid")
                        .HasColumnName("transponder_id");

                    b.HasKey("Id")
                        .HasName("pk_statistics_entry");

                    b.HasIndex("StatsProfileUserId")
                        .HasDatabaseName("ix_statistics_entry_stats_profile_user_id");

                    b.HasIndex("StatisticsItemId", "TransponderId", "TimeStart", "TimeEnd")
                        .HasDatabaseName("ix_statistics_entry_statistics_item_id_transponder_id_time_sta");

                    b.ToTable("statistics_entry", "statistics");
                });

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.StatisticsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<float>("Distance")
                        .HasColumnType("real")
                        .HasColumnName("distance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_statistics_item");

                    b.ToTable("statistics_item", "statistics");
                });

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.StatsProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_name");

                    b.HasKey("UserId")
                        .HasName("pk_stats_profile");

                    b.ToTable("stats_profile", "statistics");
                });

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.MultiStatisticsItemConfig", b =>
                {
                    b.HasOne("VeloTime.Module.Statistics.Model.SimpleStatisticsItemConfig", "ParentConfig")
                        .WithMany()
                        .HasForeignKey("ParentConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_multi_statistics_item_config_simple_statistics_item_config_");

                    b.HasOne("VeloTime.Module.Statistics.Model.StatisticsItem", "StatisticsItem")
                        .WithMany()
                        .HasForeignKey("StatisticsItemId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("fk_multi_statistics_item_config_statistics_item_statistics_ite");

                    b.Navigation("ParentConfig");

                    b.Navigation("StatisticsItem");
                });

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.SimpleStatisticsItemConfig", b =>
                {
                    b.HasOne("VeloTime.Module.Statistics.Model.StatisticsItem", "StatisticsItem")
                        .WithMany()
                        .HasForeignKey("StatisticsItemId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("fk_simple_statistics_item_config_statistics_item_statistics_it");

                    b.Navigation("StatisticsItem");
                });

            modelBuilder.Entity("VeloTime.Module.Statistics.Model.StatisticsEntry", b =>
                {
                    b.HasOne("VeloTime.Module.Statistics.Model.StatisticsItem", "StatisticsItem")
                        .WithMany()
                        .HasForeignKey("StatisticsItemId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("fk_statistics_entry_statistics_item_statistics_item_id");

                    b.HasOne("VeloTime.Module.Statistics.Model.StatsProfile", "StatsProfile")
                        .WithMany()
                        .HasForeignKey("StatsProfileUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_statistics_entry_stats_profile_stats_profile_user_id");

                    b.Navigation("StatisticsItem");

                    b.Navigation("StatsProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
