// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeloTime.Agent.Storage;

#nullable disable

namespace VeloTime.Agent.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    partial class AgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agent")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeloTime.Agent.Model.Passing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("LoopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loop_id");

                    b.Property<bool>("LowBattery")
                        .HasColumnType("boolean")
                        .HasColumnName("low_battery");

                    b.Property<bool>("LowStrength")
                        .HasColumnType("boolean")
                        .HasColumnName("low_strength");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<string>("TransponderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transponder_id");

                    b.Property<string>("TransponderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transponder_type");

                    b.HasKey("Id")
                        .HasName("pk_passing");

                    b.ToTable("passing", "agent");
                });
#pragma warning restore 612, 618
        }
    }
}
