---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-secrets"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "postgres"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres.postgres_password }}"
type: "Opaque"
