<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
	<Version>3.0.0-alpha.56</Version>
	<ContainerRepository>asbjorjo/velotime-webui-client</ContainerRepository>
	<ContainerImageTag>$(Version)</ContainerImageTag>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
	<PackageReference Include="Extensions.MudBlazor.StaticInput" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

</Project>
