<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Version>3.0.0-alpha.58</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="MR.AspNetCore.Pagination" />
	<PackageReference Include="SlimMessageBus.Host" />
    <PackageReference Include="SlimMessageBus.Host.AzureServiceBus" />
    <PackageReference Include="SlimMessageBus.Host.Serialization.SystemTextJson" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Module.Common\VeloTime.Module.Common.csproj" />
	<ProjectReference Include="..\Module.Facilities.Client\VeloTime.Module.Facilities.Client.csproj" />
    <ProjectReference Include="..\Module.Statistics.Interface\VeloTime.Module.Statistics.Interface.csproj" />
    <ProjectReference Include="..\Module.Timing.Interface\VeloTime.Module.Timing.Interface.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
