// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeloTime.Module.Facilities.Storage;

#nullable disable

namespace VeloTime.Module.Facilities.Migrations
{
    [DbContext(typeof(FacilityDbContext))]
    partial class FacilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("facility")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeloTime.Module.Facilities.Model.CourseLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.HasKey("Id")
                        .HasName("pk_course_layout");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_course_layout_facility_id");

                    b.ToTable("course_layout", "facility");
                });

            modelBuilder.Entity("VeloTime.Module.Facilities.Model.CoursePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("TimingPoint")
                        .HasColumnType("uuid")
                        .HasColumnName("timing_point");

                    b.HasKey("Id")
                        .HasName("pk_course_point");

                    b.ToTable("course_point", "facility");
                });

            modelBuilder.Entity("VeloTime.Module.Facilities.Model.CourseSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseLayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_layout_id");

                    b.Property<Guid>("EndId")
                        .HasColumnType("uuid")
                        .HasColumnName("end_id");

                    b.Property<double>("Length")
                        .HasColumnType("double precision")
                        .HasColumnName("length");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("StartId")
                        .HasColumnType("uuid")
                        .HasColumnName("start_id");

                    b.HasKey("Id")
                        .HasName("pk_course_segment");

                    b.HasIndex("CourseLayoutId")
                        .HasDatabaseName("ix_course_segment_course_layout_id");

                    b.HasIndex("EndId")
                        .HasDatabaseName("ix_course_segment_end_id");

                    b.HasIndex("StartId")
                        .HasDatabaseName("ix_course_segment_start_id");

                    b.ToTable("course_segment", "facility");
                });

            modelBuilder.Entity("VeloTime.Module.Facilities.Model.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_facility");

                    b.ToTable("facility", "facility");
                });

            modelBuilder.Entity("VeloTime.Module.Facilities.Model.CourseLayout", b =>
                {
                    b.HasOne("VeloTime.Module.Facilities.Model.Facility", "Facility")
                        .WithMany("Layouts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_layout_facility_facility_id");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("VeloTime.Module.Facilities.Model.CourseSegment", b =>
                {
                    b.HasOne("VeloTime.Module.Facilities.Model.CourseLayout", "CourseLayout")
                        .WithMany("Segments")
                        .HasForeignKey("CourseLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_segment_course_layout_course_layout_id");

                    b.HasOne("VeloTime.Module.Facilities.Model.CoursePoint", "End")
                        .WithMany()
                        .HasForeignKey("EndId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_segment_course_point_end_id");

                    b.HasOne("VeloTime.Module.Facilities.Model.CoursePoint", "Start")
                        .WithMany()
                        .HasForeignKey("StartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_segment_course_point_start_id");

                    b.Navigation("CourseLayout");

                    b.Navigation("End");

                    b.Navigation("Start");
                });

            modelBuilder.Entity("VeloTime.Module.Facilities.Model.CourseLayout", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("VeloTime.Module.Facilities.Model.Facility", b =>
                {
                    b.Navigation("Layouts");
                });
#pragma warning restore 612, 618
        }
    }
}
