<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Version>3.0.0-alpha.50</Version>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Aspire.Keycloak.Authentication" Version="13.2.0-preview.1.26170.3" />
	<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.2.0" />
	<PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.2.0" />
    <PackageReference Include="Duende.AccessTokenManagement" Version="4.2.0" />
	<PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.5" />
	<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="SlimMessageBus.Host" Version="3.4.0" />
	<PackageReference Include="ZiggyCreatures.FusionCache" Version="2.6.0" />
	<PackageReference Include="ZiggyCreatures.FusionCache.Backplane.StackExchangeRedis" Version="2.6.0" />
	<PackageReference Include="ZiggyCreatures.FusionCache.OpenTelemetry" Version="2.6.0" />
	<PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" Version="2.6.0" />
  </ItemGroup>
</Project>
