---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "keycloak-secrets"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "keycloak"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .Values.secrets.keycloak.keycloak_password }}"
  KC_DB_PASSWORD: "{{ .Values.secrets.keycloak.postgres_password }}"
type: "Opaque"
