<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-VeloTime.WebUI.Mud-30af8936-e923-4ebe-91d6-ca4269c5aae6</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
	<Version>3.0.0-alpha.56</Version>
	<ContainerRepository>asbjorjo/velotime-webui</ContainerRepository>
	<ContainerImageTag>$(Version)</ContainerImageTag>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="Aspire.Keycloak.Authentication" Version="13.4.0-preview.1.26281.18" />
	<PackageReference Include="Duende.AccessTokenManagement.OpenIdConnect" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" Version="10.6.0" />
    <PackageReference Include="Extensions.MudBlazor.StaticInput" Version="4.1.0" />
    <PackageReference Include="Microsoft.Kiota.Bundle" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NSwag.ApiDescription.Client" Version="14.7.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Module.Common\VeloTime.Module.Common.csproj" />
    <ProjectReference Include="..\Module.Facilities.Client\VeloTime.Module.Facilities.Client.csproj" />
	<ProjectReference Include="..\Module.Statistics.Client\VeloTime.Module.Statistics.Client.csproj" />
	<ProjectReference Include="..\Module.Timing.Client\VeloTime.Module.Timing.Client.csproj" />
	<ProjectReference Include="..\ServiceDefaults\VeloTime.ServiceDefaults.csproj" />
    <ProjectReference Include="..\WebUI.Mud.Client\VeloTime.WebUI.Mud.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ContainerPort Include="8081" />
  </ItemGroup>
  <ItemGroup>
	<OpenApiReference Include="..\..\api\keycloak.yaml" CodeGenerator="NSwagCSharp" Namespace="VeloTime.WebUI.Keycloak" ClassName="KeycloakClient">
	  <Options>/UseBaseUrl:false /GenerateClientInterfaces:true</Options>
	</OpenApiReference>
  </ItemGroup>
</Project>