# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - velotimer-reload

on:
  push:
    branches:
      - dockertest
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://velotimer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a71a5db593ad48e58fcde84149d8f400 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fadc9cea463d44dfb5043e565f5ff811 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: velotimer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a71a5db593ad48e58fcde84149d8f400 }}/velotimerconsole:${{ github.sha }}
        file: VelotimerConsole/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
      environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'velotimer-reload'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c14b670188b494cb65325663ae0e72f }}
        images: 'velotimer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a71a5db593ad48e58fcde84149d8f400 }}/velotimerconsole:${{ github.sha }}'
