on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Pack
      run: dotnet pack VeloTimerWeb/Shared --configuration Release /p:Version=${env:VERSION} --output .
    - name: Pack
      run: dotnet pack Shared.Data --configuration Release /p:Version=${env:VERSION} --output .
    - name: Pack
      run: dotnet pack Shared.Services --configuration Release /p:Version=${env:VERSION} --output .
    - name: Push
      run: dotnet nuget push VeloTimer.*.${env:VERSION}.nupkg --source https://nuget.pkg.github.com/asbjorjo/index.json --api-key ${env:NUGET_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}