name: Build and deploy to Azure production environment
on:
  push:
    branches:
    - staging   
env:
  AZURE_WEBAPP_NAME: velotime-noe
  AZURE_AMMC_NAME: velotime-noe-ammc
  AZURE_API_PACKAGE_PATH: VeloTimerWeb.Api/publish
  AZURE_AMMC_PACKAGE_PATH: VeloTimer.AmccLoad/publish
  CONFIGURATION: Release
  ASPNETCORE_ENVIRONMENT: Production
  DOTNET_CORE_VERSION: 5.0.x
  API_WORKING_DIRECTORY: VeloTimerWeb.Api
  AMMC_WORKING_DIRECTORY: VeloTimer.AmmcLoad
  AzureVault: https://velotime-vault.vault.azure.net/
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_PRODUCTION_CREDENTIALS }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test --no-build
    - name: Publish API
      run: dotnet publish "${{ env.API_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_API_PACKAGE_PATH }}"
    - name: Publish AmmcLoad
      run: dotnet publish "${{ env.AMMC_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_AMMC_PACKAGE_PATH }}"
    - name: Install EF Tool
      run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
    - name: Update Identity Database
      run: dotnet ef database update -p ${{ env.API_WORKING_DIRECTORY }} -s ${{ env.API_WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} -c VeloIdentityDbContext --no-build
    - name: Update VeloTimer Database
      run: dotnet ef database update -p ${{ env.API_WORKING_DIRECTORY }} -s ${{ env.API_WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} -c VeloTimerDbContext --no-build
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: github-ci
        package: ${{ env.AZURE_API_PACKAGE_PATH }}
    - name: Deploy to Azure AmmcLoader
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_AMMC_NAME }}
        package: ${{ env.AZURE_AMMC_PACKAGE_PATH }}
    - name: Publish API Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: api
        path: ${{ env.AZURE_API_PACKAGE_PATH }}
    - name: Publish AmmcLoad Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ammcload
        path: ${{ env.AZURE_AMMC_PACKAGE_PATH }}
    - name: Azure Logout
      run: az logout
